package com.javamastery.jvm;

/**
 * A simple class for bytecode analysis.
 *
 * After compiling, run:
 *   javap -c -v target/classes/com/javamastery/jvm/BytecodeDemo.class
 *
 * This shows the bytecode instructions generated by javac.
 */
public class BytecodeDemo {

    private int counter;

    public static void main(String[] args) {
        System.out.println("=== Bytecode Basics Demo ===\n");
        System.out.println("Compile and view bytecode with:");
        System.out.println("  javap -c -v target/classes/com/javamastery/jvm/BytecodeDemo.class\n");

        BytecodeDemo demo = new BytecodeDemo();
        int result = demo.add(3, 4);
        System.out.println("add(3, 4) = " + result);

        String greeting = demo.greet("World");
        System.out.println(greeting);

        demo.incrementCounter();
        demo.incrementCounter();
        System.out.println("Counter: " + demo.counter);

        System.out.println("\n--- Key Bytecode Instructions ---");
        System.out.println("  aload_0     : load 'this' reference onto operand stack");
        System.out.println("  iload_1     : load int parameter 1 onto stack");
        System.out.println("  iadd        : pop two ints, add, push result");
        System.out.println("  ireturn     : return int from method");
        System.out.println("  invokevirtual  : call instance method (dynamic dispatch)");
        System.out.println("  invokespecial  : call constructor or super method");
        System.out.println("  invokestatic   : call static method");
        System.out.println("  invokeinterface: call interface method");
        System.out.println("  new         : allocate object (uninitialized)");
        System.out.println("  dup         : duplicate top of stack (for constructor call after new)");
        System.out.println("  getfield    : read instance field");
        System.out.println("  putfield    : write instance field");
        System.out.println("  getstatic   : read static field");
        System.out.println("  ldc         : load constant from constant pool");
    }

    /**
     * Simple addition — look for: iload_1, iload_2, iadd, ireturn
     */
    public int add(int a, int b) {
        return a + b;
    }

    /**
     * String concatenation — look for: invokedynamic (StringConcatFactory)
     * Since Java 9, string concat uses invokedynamic for performance.
     */
    public String greet(String name) {
        return "Hello, " + name + "!";
    }

    /**
     * Field access — look for: getfield, iconst_1, iadd, putfield
     */
    public void incrementCounter() {
        this.counter++;
    }
}
